export const siteMetadata = {
    title: 'Blogix',
    author: 'Bora Deniz Baş',
    headerTitle: 'Next.js Blog',
    description: 'Nextjs practice project',
    language: 'en-us',
    theme: 'system',
    siteUrl: ' ',
    siteLogo: '/file.svg',
    socialBanner: "",
    email: 'boradenizbas1@gmail.com',
    github: 'https://github.com/KahweB',
    twitter: '',
    facebook: '',
    youtube: '',
    linkedin: '',
    dribbble: '',
    locale: 'en-US',
}